= Sweet Tooth endpoint =
Daniel Higginbotham


The https://github.com/sweet-tooth-clojure/endpoint[Sweet Tooth endpoint library] helps you create an API server.

xref:routes-and-handlers:index.adoc[*Routes and Handlers*] explains how to write
API routes and endpoint handlers. Sweet Tooth introduces helpers that allow you
to write compact routes that can be shared between backend and frontend. It uses
the Liberator library for generating endpoint handlers; Liberator is explained,
along with Sweet Tooth's helpers. The guide also describes the response protocol
that Sweet Tooth introduces.

xref:architecture:index.adoc[*Server Architecture: Components and Beyond*]
describes the architecture of Sweet Tooth API servers and the tools used to
implement the architecture. It covers:

* The components involved in handling a request
* The relationships among the components
* The Integrant and Duct libraries, and how to use them to compose and manage
the components

xref:systems:index.adoc[*Systems*] reviews the `sweet-tooth.endpoint.system`
namespace and its tools for managing integrant configs and specifying
altnernative component implementations.
