= Endpoint Routes and Handlers =
Daniel Higginbotham


This doc explains how to write endpoint _routes_ and _handlers_ in a Sweet Tooth
app.

*Routes* have two main purposes:

* Conveying requests to a handler
* Generating paths using a route name and parameters

For a more detailed explanation of routes and routing, see
xref:routes-and-routing-explained.adoc[Routes and Routing Explained].

Sweet Tooth relies on the reitit routing library, which represents routes as
two-element vectors that associate URL patterns like `/users/{id}` with a map
containing the route's name, handler, and metadata. For example:

[source,clojure]
.route example
----
["/users/{id}" {:name    :users
                :handler (fn [req] {:body "response"})}]
----

*Handlers* are functions that take a request as an argument and return a response.

Sweet Tooth introduces conventions for associating route paths, route names, and
the namespaces that hold handler definitions. This section is a practical
tutorial on what steps to take to get things working. Further sections go into
more detail about the implementation so that you'll understand how to customize
the system to your particular needs, if you need to.

These docs assume you're working within the https://github.com/sweet-tooth-clojure/todo-example[the Sweet Tooth To-Do List Example]
project.


== Basic Routes and Handlers ==
Sweet Tooth is oriented around RESTful APIs. You send `GET`, `POST`, `PUT`, and
`DELETE` requests to paths like `/todo-list` and `/todo-list/1` in order to
perform CRUD operations. The corresponding request handlers are located in a
namespace like `sweet-tooth.todo-example.backend.endpoint.todo-list`.

The `sweet-tooth.todo-example.cross.endpoint-routes/expand-routes` function lets
you specify the names of namespaces that contain handlers and uses those to
generate routes. Let's generate some simple routes in a REPL and work our way up
to more complex ones:

[source,clojure]
.basic namespace route
----
(require '[sweet-tooth.endpoint.routes.reitit :as serr])
(serr/expand-routes [[:sweet-tooth.todo-example.backend.endpoint.todo-list]])

;; =>
[["/todo-list"
  {::serr/ns   :sweet-tooth.todo-example.backend.endpoint.todo-list
   ::serr/type :collection
   :name       :todo-lists}]
 ["/todo-list/{id}"
  {::serr/ns   :sweet-tooth.todo-example.backend.endpoint.todo-list
   ::serr/type :member
   :name       :todo-list
   :id-key     :id}]]
----

The function took a single keyword corresponding to a namespace's name and
generated two routes for it, one with the path `"/todo-list"` named
`:todo-lists` and one with the path `"/todo-list/{id}" `named `:todo-list`.
These paths and names are derived from the namespace name, with `endpoint.` as
the default delimiter.

You'll also see some metadata keys, `::serr/ns`, `::serr/type`, and `:id-key`.
Routes convey a request to the correct handler, and the `:serr/ns` and
`::serr/type` help to do this. The `::serr/ns` is used during system
initialization to find the the routes' handlers. By default, these are defined
in a var named `decisions`. If you look at
`sweet-tooth.todo-example.backend.endpoint.todo-list` namespace you'll see
something like this (I've elided irrelevant code):

[source,clojure]
.decisions
----
(def decisions
  {:collection
   {:get  {:handle-ok (comp tl/todo-lists ed/db)}
    :post {:post!          ed/create->:result
           :handle-created ed/created-pull}}

   :member
   {:get {:handle-ok (fn [ctx])}
    :put {:put!      ed/update->:result
          :handle-ok ed/updated-pull}

    :delete {:delete!   (fn [ctx])
             :handle-ok []}}})
----

`decisions` is a map whose keys correspond to `::serr/type` in the routes above:
if a request for `"/todo-list"` is received, the `::serr/type` value of
`:collection` is used to look up the map of handlers under `:collection` in the
`decisions` var. The request method (`:get`, `:post`, `:put` etc) is then used
to look up a https://clojure-liberator.github.io/liberator/[liberator] decision map. If you're unfamiliar with liberator this
probably looks weird as all get out. I'll explain liberator elsewhere, for now
we're just focusing on the relationship between routes and handlers.

To summarize:

* There is a relationship between route paths, route names, namespaces, and
handlers
* Handlers are defined as liberator decision maps
* Those decision maps live in a var named `decisions`
* `decisions` is a map keyed by route type (`:collection`, `:member`) and
request method (`:get`, `:post` etc)
* You can generate routes for an endpoint namespace using
`sweet-tooth.endpoint.routes.reitit/expand-routes`. Route paths and names are
derived from namespace names.


== Route Expanders ==
What if you only want to generate a `:collection` route or only want to generate
a `:member` route? Routes can take an option map, and you can specify which
routes to generate with the key `::serr/expand-with`:

[source,clojure]
.route generators
----
(serr/expand-routes [[:project.endpoint.todo-list {::serr/expand-with [:collection]}]])
;; =>
[["/todo-list"
  {:sweet-tooth.endpoint.routes.reitit/ns :project.endpoint.todo-list,
   :sweet-tooth.endpoint.routes.reitit/type :collection,
   :name :todo-lists}]]
----

Notice that the value of for `::serr/expand-with` is `[:collection]` and only a
`:collection` route was generated. You can try this with `[:member]` to see what
happens. The default value for `::serr/expand-with` is `[:collection :member]`.

In this context, `:collection` and `:member` are names of _route types_. Each
route type has an expansion strategy associated with. The expansion strategy
includes:

* A rule for deriving the route's name from the namespace's name. The
`:collection` strategy produces a route named `:todo-lists` when given a
namespace name `:x.endpoint.todo-list`; `:member` produces a route named
`:todo-list`.
* A rule for deriving the route's path from the namespace's name. The
`:collection` strategy generates the path `/todo-list` and `:member` generates
`/todo-list/{id}`.

In later sections you'll see how to work with additional kinds of route types,
include `:singleton`, `:member` children, and arbitrary types.


== Custom Route Paths and Names ==
What if you want to create routes that match paths like the following?

* `/api/v1/todo-list`
* `/todo-lists`
* `/todo-list/{id}/todo-items`
* `/admin/todo-list`


=== Custom Route Paths: prefixes and suffixes ===
You can specify paths with the keys `::serr/path-prefix` and
`:serr/path-suffix`:

[source,clojure]
.path prefixes
----
(serr/expand-routes [[:project.endpoint.todo-list {::serr/path-prefix "/api/v1"}]])
;; =>
[["/api/v1/todo-list"
  {::serr/ns   :project.endpoint.todo-list
   ::serr/type :collection
   :name       :todo-lists}]
 ["/api/v1/todo-list/{id}"
  {::serr/ns   :project.endpoint.todo-list
   ::serr/type :member
   :name       :todo-list
   :id-key     :id}]]
----




=== Custom Route Paths per route type ===


=== Member Routes ===

=== Nested Routes ===

=== Completely Arbitrary Routes ===


== Shared Options ==


== Defining Handlers ==





== notes to self ==
* the mechanical process, do this
* cross-compiled endpoint routes
* relationships among namespace names, route names, paths, handler
definitions, and integrant
* route expansion
* generating integrant config
* liberator
* integrant

=== how to make this interactive? ===

=== what's the flow here? ===
